init -3 python:
    ENUM__SENSUAL_SKILLS__KISSING = "ENUM__SENSUAL_SKILLS__KISSING"
    ENUM__SENSUAL_SKILLS__FELLATIO = "ENUM__SENSUAL_SKILLS__FELLATIO"
    ENUM__SENSUAL_SKILLS__CUNNILINGUS = "ENUM__SENSUAL_SKILLS__CUNNILINGUS"
    ENUM__SENSUAL_SKILLS__ANALINGUS = "ENUM__SENSUAL_SKILLS__ANALINGUS"
    ENUM__SENSUAL_SKILLS__MASTURBATION = "ENUM__SENSUAL_SKILLS__MASTURBATION"
    ENUM__SENSUAL_SKILLS__HANDJOB = "ENUM__SENSUAL_SKILLS__HANDJOB"
    ENUM__SENSUAL_SKILLS__FINGERING = "ENUM__SENSUAL_SKILLS__FINGERING"
    ENUM__SENSUAL_SKILLS__BREASTPLAY = "ENUM__SENSUAL_SKILLS__BREASTPLAY"
    ENUM__SENSUAL_SKILLS__RECEIVEVAGINALPENETRATION = "ENUM__SENSUAL_SKILLS__RECEIVEVAGINALPENETRATION"
    ENUM__SENSUAL_SKILLS__RECEIVEANALPENETRATION = "ENUM__SENSUAL_SKILLS__RECEIVEANALPENETRATION"
    ENUM__SENSUAL_SKILLS__PERFORMVAGINALPENETRATION = "ENUM__SENSUAL_SKILLS__PERFORMVAGINALPENETRATION"
    ENUM__SENSUAL_SKILLS__PERFORMORALPENETRATION = "ENUM__SENSUAL_SKILLS__PERFORMORALPENETRATION"
    ENUM__SENSUAL_SKILLS__PERFORMANALPENETRATION = "ENUM__SENSUAL_SKILLS__PERFORMANALPENETRATION"
    ENUM__SENSUAL_SKILLS__SENSUALBODYLANGUAGE = "ENUM__SENSUAL_SKILLS__SENSUALBODYLANGUAGE"
    ENUM__SENSUAL_SKILLS__RECEIVEBONDAGE = "ENUM__SENSUAL_SKILLS__RECEIVEBONDAGE"
    ENUM__SENSUAL_SKILLS__PERFORMBONDAGE = "ENUM__SENSUAL_SKILLS__PERFORMBONDAGE"

    ENUM__EROGENOUS_ZONE_SENSITIVITY__INSENSITIVE = "ENUM__EROGENOUS_ZONE_SENSITIVITY__INSENSITIVE"
    ENUM__EROGENOUS_ZONE_SENSITIVITY__DULLED = "ENUM__EROGENOUS_ZONE_SENSITIVITY__DULLED"
    ENUM__EROGENOUS_ZONE_SENSITIVITY__SOOTHING = "ENUM__EROGENOUS_ZONE_SENSITIVITY__SOOTHING"
    ENUM__EROGENOUS_ZONE_SENSITIVITY__SENSITIVE = "ENUM__EROGENOUS_ZONE_SENSITIVITY__SENSITIVE"
    ENUM__EROGENOUS_ZONE_SENSITIVITY__OVERSENSITIVE = "ENUM__EROGENOUS_ZONE_SENSITIVITY__OVERSENSITIVE"

    ENUM__EROGENOUS_ZONES__GLANS = "ENUM__EROGENOUS_ZONES__GLANS" # Penis-Head
    ENUM__EROGENOUS_ZONES__PENIS_SHAFT = "ENUM__EROGENOUS_ZONES__PENIS_SHAFT"
    ENUM__EROGENOUS_ZONES__SCROTUM = "ENUM__EROGENOUS_ZONES__SCROTUM" # Ballsack
    ENUM__EROGENOUS_ZONES__PENIS_BASE = "ENUM__EROGENOUS_ZONES__PENIS_BASE"

    ENUM__EROGENOUS_ZONES__CLITORIS = "ENUM__EROGENOUS_ZONES__CLITORIS"
    ENUM__EROGENOUS_ZONES__LABIA = "ENUM__EROGENOUS_ZONES__LABIA"
    ENUM__EROGENOUS_ZONES__VAGINA = "ENUM__EROGENOUS_ZONES__VAGINA" # Channel
    ENUM__EROGENOUS_ZONES__BREASTS = "ENUM__EROGENOUS_ZONES__BREASTS"
    
    ENUM__EROGENOUS_ZONES__MOUTH = "ENUM__EROGENOUS_ZONES__MOUTH" # or Tongue
    ENUM__EROGENOUS_ZONES__THROAT = "ENUM__EROGENOUS_ZONES__THROAT"
    ENUM__EROGENOUS_ZONES__STOMACH = "ENUM__EROGENOUS_ZONES__STOMACH" # Belly
    ENUM__EROGENOUS_ZONES__NIPPLES = "ENUM__EROGENOUS_ZONES__NIPPLES"
    ENUM__EROGENOUS_ZONES__THIGHS = "ENUM__EROGENOUS_ZONES__THIGHS"
    ENUM__EROGENOUS_ZONES__BUTTOCKS = "ENUM__EROGENOUS_ZONES__BUTTOCKS"
    ENUM__EROGENOUS_ZONES__ANUS = "ENUM__EROGENOUS_ZONES__ANUS"
    ENUM__EROGENOUS_ZONES__RECTUM = "ENUM__EROGENOUS_ZONES__RECTUM"

    class Character_Sexuality(renpy.store.object):
        def __init__(self):
            return
        
        def generate_random(gender):
            result = Character_Sexuality()
            if (gender == GENDER__FEMALE):
                return Character_Sexuality._generate_random_female_sexuality()
            else:
                return Character_Sexuality._generate_random_male_sexuality()
        
        def _generate_random_female_sexuality():
            return result

        def _generate_random_male_sexuality():
            return result