ENUM__TIME_CONTROL__DAY_PART__LATE_NIGHT = "EARLY_NIGHT"       # 0 - 3
ENUM__TIME_CONTROL__DAY_PART__LATE_NIGHT = "LATE_NIGHT"        # 3 - 6
ENUM__TIME_CONTROL__DAY_PART__EARLY_MORNING = "EARLY_MORNING"     # 6 - 9
ENUM__TIME_CONTROL__DAY_PART__LATE_MORNING = "LATE_MORNING"      # 9 - 12
ENUM__TIME_CONTROL__DAY_PART__EARLY_AFTERNOON = "EARLY_AFTERNOON"   # 12 - 15
ENUM__TIME_CONTROL__DAY_PART__LATE_AFTERNOON = "LATE_AFTERNOON"    # 15 - 18
ENUM__TIME_CONTROL__DAY_PART__EARLY_EVENING = "EARLY_EVENING"     # 18 - 21
ENUM__TIME_CONTROL__DAY_PART__LATE_EVENING = "LATE_EVENING"      # 21 - 24

ENUM__TIME_CONTROL__WEEK_DAY__SUNDAY__INDEX = 0
ENUM__TIME_CONTROL__WEEK_DAY__MONDAY__INDEX = 1
ENUM__TIME_CONTROL__WEEK_DAY__TUESDAY__INDEX = 2
ENUM__TIME_CONTROL__WEEK_DAY__WEDNESDAY__INDEX = 3
ENUM__TIME_CONTROL__WEEK_DAY__THURSDAY__INDEX = 4
ENUM__TIME_CONTROL__WEEK_DAY__FRIDAY__INDEX = 5
ENUM__TIME_CONTROL__WEEK_DAY__SATURDAY__INDEX = 6
